// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Episode struct {
	FileName string `json:"fileName"`
	Number   int    `json:"number"`
	Label    string `json:"label"`
}

type InputSerie struct {
	Work bool `json:"work"`
}

type Season struct {
	DirectoryName string     `json:"directoryName"`
	Number        int        `json:"number"`
	Label         string     `json:"label"`
	Episodes      []*Episode `json:"episodes"`
}

type Serie struct {
	DirectoryName string    `json:"directoryName"`
	Label         string    `json:"label"`
	Seasons       []*Season `json:"seasons"`
}
